### PR TITLE
Fixed link / Added ApiDoc

### PR DESCRIPTION
**Pull request by trenton42**
- Heading changed but link hash did not
- Added link to ApiDoc generator

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks, Trenton. Take a second to add an attribution to your contrib and I'll get it merged.

**Comment by trenton42** [comment]
Thanks @PharkMillups!

**Comment by PharkMillups** [comment]
Merged manually. Sorry for the long delay here, Trenton .

**Comment by trenton42** [comment]
No worries! Thanks for the merge @PharkMillups 👍

**Pull request closed without merging**
