### PR TITLE
Add Atlassian GIT Tutorial

### PR DESCRIPTION
**Pull request by vaseev**

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks for the contribution.  I'm happy to add these. Fix that typo when you get a moment and I'll merge.

**Comment by vaseev** [comment]
Hi Mark

Hope all is well.

I know you are busy. Any chance of having my changes (pull request #122)
pulled into your master?
I think I have fixed things on my end.


Regards
Vasee

**Comment by flynnduism** [comment]
+1 for this, one of the slickest (and quickest) documentation sites I've ever seen.

**Comment by PharkMillups** [comment]
Finally got this merged in. Thanks for the patience, @vaseev.

**Pull request closed without merging**
